server:
  port: 8085

spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      routes:
        - id: medical-services
          uri: lb://medical-services
          predicates:
            - Path=/api/**

        - id: userlogin-service
          uri: lb://userlogin-service
          predicates:
            - Path=/api/**

        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/api/**

        - id: food-service
          uri: lb://food-service
          predicates:
            - Path=/api/**

        - id: cinema-service
          uri: lb://cinema-service
          predicates:
            - Path=/api/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/